## 1-NN Algorithm Regression Problem

In [66]:
# importing required library
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [67]:
# Reading Data
cars = pd.read_csv('cars.csv')
cars = cars.drop(['Car','Model','Origin'], axis = 1)

In [68]:
cars.head(5)

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration
0  18.0          8         307.0         130    3504          12.0
1  15.0          8         350.0         165    3693          11.5
2  18.0          8         318.0         150    3436          11.0
3  16.0          8         304.0         150    3433          12.0
4  17.0          8         302.0         140    3449          10.5

In [69]:
cars.describe()

MPG   Cylinders  Displacement  Horsepower       Weight  \
count  406.000000  406.000000    406.000000  406.000000   406.000000   
mean    23.051232    5.475369    194.779557  103.529557  2979.413793   
std      8.401777    1.712160    104.922458   40.520659   847.004328   
min      0.000000    3.000000     68.000000    0.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2226.500000   
50%     22.350000    4.000000    151.000000   93.500000  2822.500000   
75%     29.000000    8.000000    302.000000  129.000000  3618.250000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       Acceleration  
count    406.000000  
mean      15.519704  
std        2.803359  
min        8.000000  
25%       13.700000  
50%       15.500000  
75%       17.175000  
max       24.800000

In [70]:
# Assigning Predictor/Features & Target/Label 
x = cars[['Displacement','Cylinders', 'Horsepower', 'Weight','Acceleration']]
y = cars['MPG']

In [71]:
# Splinting Data for test-train using train_test_splitabs
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 10)

In [72]:
type(y_test)

pandas.core.series.Series

In [73]:
print(f'x_train data: \n{ x_train.head(2)}')
print(f'x_test data: \n{x_test.head(2)}')
print(f'y_train data: \n{y_train.head(2)}')
print(f'y_test data: \n{y_test.head(2)}')

x_train data: 
     Displacement  Cylinders  Horsepower  Weight  Acceleration
114         232.0          6         100    2789          15.0
205          91.0          4          53    1795          17.4
x_test data: 
     Displacement  Cylinders  Horsepower  Weight  Acceleration
166         351.0          8         148    4657          13.5
1           350.0          8         165    3693          11.5
y_train data: 
114    18.0
205    33.0
Name: MPG, dtype: float64
y_test data: 
166    14.0
1      15.0
Name: MPG, dtype: float64


### Scaling Data to standardized

In [74]:
import scipy.stats as st

In [75]:
x_train = pd.DataFrame(st.zscore(x_train))
                                                            #y_train = pd.DataFrame(st.zscore(y_train))
x_test = pd.DataFrame(st.zscore(x_test))
                                                            #y_test = pd.DataFrame(st.zscore(y_test))

In [76]:
type(x_train)

pandas.core.frame.DataFrame

In [77]:
x_train.head(5)

0         1         2         3         4
0  0.394120  0.332706 -0.047462 -0.196042 -0.205585
1 -0.996990 -0.863351 -1.242800 -1.436781  0.638553
2 -0.937794 -0.863351 -1.420829 -1.386852  1.728898
3 -1.056187 -0.863351 -0.937608 -1.155930  1.271657
4 -0.464225  0.332706 -0.657848  0.267051  1.412346

### Function 1
### * To calculate Eclidean Distance between two Vector

In [78]:
# Euclidean Distance function using "for loop" method 
def DISTANCE(x,y):
    distance = np.sqrt(np.sum((x-y)**2))  
    return(distance)


In [79]:
DISTANCE(x_train.iloc[108,],x_test.iloc[0,])

0.32365443584157716

In [80]:
# Euclidean Distance function using Vectorized Notation 
def DIST(x,y):
    distance = np.sqrt(np.dot((x-y), np.transpose(x-y)))
    return(distance)


In [81]:
DIST(x_train.iloc[108,],x_test.iloc[0,])

0.3236544358415772

### Function 2
### * To calculate NN for one test observation

In [82]:
# Importing Math Libaray
import math
x_star = x_test.iloc[0,]

In [83]:
# Function to Calaulate 1-NN with one obs in Test data set
def NN(x_train, y_train, x_star):
    import math
    min_dist = math.inf
    for i in range(len(x_train)):
        dist = DISTANCE(x_train.iloc[i,], x_star)
        
        if dist < min_dist:
            min_dist = dist
            index = i
    #print(f'Minimum Distance is : {min_dist}')
    #print(f"index is {index}")
    return(np.array(y_train)[index])
    

In [84]:
NN(x_train, y_train, x_star)

15.5

In [85]:
print(f'Predicted Value: {y_train.iloc[108]}')

Predicted Value: 15.5


In [86]:
print(f'Actual Value: {y_test.iloc[0]}')

Actual Value: 14.0


In [53]:
def one_NN(x_train, y_train, x_test):
    y_pred = []
    for i in range(len(x_test)):
        y_pred.append(NN(x_train, y_train, x_test.iloc[i,]))
    return(y_pred)

In [54]:
y_pred = one_NN(x_train, y_train, x_test)
y_pred

[15.5,
 18.0,
 17.0,
 26.0,
 26.0,
 46.6,
 13.0,
 44.0,
 26.0,
 19.1,
 13.0,
 24.0,
 26.4,
 29.5,
 19.0,
 25.0,
 33.0,
 23.0,
 40.8,
 27.0,
 21.1,
 17.5,
 18.0,
 31.5,
 24.5,
 14.0,
 17.6,
 18.1,
 13.0,
 13.0,
 18.0,
 14.0,
 25.8,
 17.0,
 29.0,
 14.0,
 0.0,
 22.0,
 13.0,
 20.5,
 31.8,
 14.0,
 28.0,
 15.5,
 18.1,
 36.1,
 31.0,
 36.0,
 25.0,
 38.1,
 11.0,
 32.0,
 22.5,
 14.0,
 14.0,
 26.0,
 14.0,
 15.0,
 32.1,
 31.6,
 31.0,
 19.8,
 22.5,
 34.2,
 36.0,
 22.0,
 25.0,
 0.0,
 30.0,
 20.0,
 17.0,
 44.3,
 15.0,
 28.0,
 24.2,
 20.2,
 19.0,
 17.0,
 13.0,
 19.9,
 26.0,
 37.0,
 28.0,
 32.3,
 26.0,
 24.2,
 22.0,
 20.2,
 19.2,
 26.0,
 29.0,
 38.0,
 26.0,
 44.3,
 15.0,
 18.0,
 16.2,
 27.0,
 15.0,
 25.0,
 10.0,
 18.0,
 15.5,
 36.0,
 26.0,
 35.0,
 40.9,
 29.5,
 23.0,
 20.5,
 13.0,
 24.0,
 20.2,
 21.5,
 24.0,
 29.8,
 14.0,
 27.0,
 17.0,
 29.0,
 21.0,
 28.0]

### Function 3
### * To Find 1NN for all the Observation in Test Data.

In [24]:
import math

In [25]:
## Function to Calaulate 1-NN with one obs in Test data set

def one_NN(x_train, y_train, x_test):
    
    y_pred = []
    for i in range(len(x_test)): # selecting ony by one obs. in test data
        j = 0
        min_dist = math.inf
        for j in range(len(x_train)):  # selecting ony by one obs. in train data
            dist = DIST(x_test.iloc[i,], x_train.iloc[j,])
            if dist < min_dist:
                min_dist = dist
                index_train = j
        index_test = i
        #y_pred.append(((np.array(y_train)[index_train]), round(min_dist,2), index_train, index_test))
        y_pred.append(((np.array(y_train)[index_train])))
    return(y_pred)
    

In [27]:
y_pred = one_NN(x_train, y_train, x_test)
y_pred;

[array([-0.96248842]),
 array([-0.661074]),
 array([-0.78163977]),
 array([0.30345215]),
 array([0.30345215]),
 array([2.78710699]),
 array([-1.26390284]),
 array([2.47363599]),
 array([0.30345215]),
 array([-0.52845165]),
 array([-1.26390284]),
 array([0.06232062]),
 array([0.35167846]),
 array([0.72543234]),
 array([-0.54050823]),
 array([0.18288638]),
 array([1.14741254]),
 array([-0.05824515]),
 array([2.08782553]),
 array([0.42401792]),
 array([-0.28732011]),
 array([-0.72135688]),
 array([-0.661074]),
 array([0.96656388]),
 array([0.1226035]),
 array([-1.14333707]),
 array([-0.70930031]),
 array([-0.64901742]),
 array([-1.26390284]),
 array([-1.26390284]),
 array([-0.661074]),
 array([-1.14333707]),
 array([0.279339]),
 array([-0.78163977]),
 array([0.66514946]),
 array([-1.14333707]),
 array([-2.83125784]),
 array([-0.17881092]),
 array([-1.26390284]),
 array([-0.35965958]),
 array([1.00273361]),
 array([-1.14333707]),
 array([0.54458369]),
 array([-0.96248842]),
 array([-0.6490

In [30]:
print(f'Predicted Value: {y_train.iloc[139]}')
print(f'Actual Value: {y_test.iloc[121]}')

Predicted Value: 0    0.544584
Name: 139, dtype: float64
Actual Value: 0    0.932578
Name: 121, dtype: float64


In [55]:
type(y_pred)

list

In [56]:
y_pred = np.array(y_pred)
y_test = np.array(y_test)

In [57]:
y_pred.reshape(122,1)
y_pred.shape

(122,)

In [58]:
y_test.reshape(122,1)
y_test.shape

(122,)

In [60]:
# for comparing Errors
from sklearn import metrics
# Root Mean Squared Error
print(f'Root Mean Squared Error: {np.sqrt(metrics.mean_squared_error(y_test, y_pred))}')

Root Mean Squared Error: 6.693616974156896
